@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3ODAyMDUwNywiZXhwIjoxNzc4MDQ5MzA3fQ.nspIOL8yE7038O6NklodIUFfBWp3ryQmpSMK5Fr-kDY

GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/active

###
GET http://localhost:3000/api/users/3

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Pedro",
  "lastName": "Teste",
  "phone": "2499999-5421",
  "email": "p@p.com",
  "password": "david1234!"
}

###

DELETE http://localhost:3000/api/users/2

###

PATCH  http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "Hansen de Oliveira 22"
}

###
PATCH  http://localhost:3000/api/users/4/toggle

###
PATCH  http://localhost:3000/api/users/role/12
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "admin"
}
